mysql:
  image: mysql:8.0
  storage: 5Gi
  rootPassword: root
  database: ecommerce

backend:
  image: hemanth0804/helm_backend:v1
  replicas: 2
  port: 8080
  nodePort: 30083

frontend:
  image: hemanth0804/helm_frontend:v1
  replicas: 2
  port: 8080
  nodePort: 30082

ingress:
  enabled: true
  host: ecommerce.local

autoscaling:
  backend:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 60

  frontend:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 60
